#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPC.NugetServer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HWMS_DEV")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertPACK_CTN(PACK_CTN instance);
    partial void UpdatePACK_CTN(PACK_CTN instance);
    partial void DeletePACK_CTN(PACK_CTN instance);
    partial void InsertPACK_HDR(PACK_HDR instance);
    partial void UpdatePACK_HDR(PACK_HDR instance);
    partial void DeletePACK_HDR(PACK_HDR instance);
    partial void InsertPACK_DTL(PACK_DTL instance);
    partial void UpdatePACK_DTL(PACK_DTL instance);
    partial void DeletePACK_DTL(PACK_DTL instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HWMS_DEVConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PACK_CTN> PACK_CTN
		{
			get
			{
				return this.GetTable<PACK_CTN>();
			}
		}
		
		public System.Data.Linq.Table<PACK_HDR> PACK_HDR
		{
			get
			{
				return this.GetTable<PACK_HDR>();
			}
		}
		
		public System.Data.Linq.Table<PACK_DTL> PACK_DTL
		{
			get
			{
				return this.GetTable<PACK_DTL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PACK_CTN")]
	public partial class PACK_CTN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WORK_CENTER;
		
		private string _STORER_ID;
		
		private string _PACK_ID;
		
		private string _CARTON_NO;
		
		private string _CARTON_TYPE;
		
		private long _CTN_LINE_SEQ;
		
		private System.Nullable<decimal> _LENGTH;
		
		private System.Nullable<decimal> _WIDTH;
		
		private System.Nullable<decimal> _HEIGHT;
		
		private System.Nullable<decimal> _CTN_VOLUME;
		
		private System.Nullable<decimal> _CTN_GROSS_WEIGHT;
		
		private System.Nullable<decimal> _CTN_NET_WEIGHT;
		
		private string _CARRIER;
		
		private string _TRACKING_NO;
		
		private string _PALLET_NO;
		
		private string _BUILD_PALLET_BY;
		
		private System.Nullable<System.DateTime> _BUILD_PALLET_DATE;
		
		private System.Nullable<int> _BUILD_PALLET_SEQ;
		
		private string _CONTAINER_NO;
		
		private string _CONTAINER_TYPE;
		
		private string _SEAL_NO;
		
		private string _SCAN_LOAD_BY;
		
		private System.Nullable<System.DateTime> _SCAN_LOAD_DATE;
		
		private System.Nullable<long> _SCAN_LOAD_SEQ;
		
		private string _REMARKS;
		
		private System.Nullable<int> _VERSION;
		
		private string _CREATE_BY;
		
		private System.DateTime _CREATE_DATE;
		
		private string _MODIFY_BY;
		
		private System.Nullable<System.DateTime> _MODIFY_DATE;
		
		private string _PACKING_MATERIALS;
		
		private string _BENCH_NO;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWORK_CENTERChanging(string value);
    partial void OnWORK_CENTERChanged();
    partial void OnSTORER_IDChanging(string value);
    partial void OnSTORER_IDChanged();
    partial void OnPACK_IDChanging(string value);
    partial void OnPACK_IDChanged();
    partial void OnCARTON_NOChanging(string value);
    partial void OnCARTON_NOChanged();
    partial void OnCARTON_TYPEChanging(string value);
    partial void OnCARTON_TYPEChanged();
    partial void OnCTN_LINE_SEQChanging(long value);
    partial void OnCTN_LINE_SEQChanged();
    partial void OnLENGTHChanging(System.Nullable<decimal> value);
    partial void OnLENGTHChanged();
    partial void OnWIDTHChanging(System.Nullable<decimal> value);
    partial void OnWIDTHChanged();
    partial void OnHEIGHTChanging(System.Nullable<decimal> value);
    partial void OnHEIGHTChanged();
    partial void OnCTN_VOLUMEChanging(System.Nullable<decimal> value);
    partial void OnCTN_VOLUMEChanged();
    partial void OnCTN_GROSS_WEIGHTChanging(System.Nullable<decimal> value);
    partial void OnCTN_GROSS_WEIGHTChanged();
    partial void OnCTN_NET_WEIGHTChanging(System.Nullable<decimal> value);
    partial void OnCTN_NET_WEIGHTChanged();
    partial void OnCARRIERChanging(string value);
    partial void OnCARRIERChanged();
    partial void OnTRACKING_NOChanging(string value);
    partial void OnTRACKING_NOChanged();
    partial void OnPALLET_NOChanging(string value);
    partial void OnPALLET_NOChanged();
    partial void OnBUILD_PALLET_BYChanging(string value);
    partial void OnBUILD_PALLET_BYChanged();
    partial void OnBUILD_PALLET_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBUILD_PALLET_DATEChanged();
    partial void OnBUILD_PALLET_SEQChanging(System.Nullable<int> value);
    partial void OnBUILD_PALLET_SEQChanged();
    partial void OnCONTAINER_NOChanging(string value);
    partial void OnCONTAINER_NOChanged();
    partial void OnCONTAINER_TYPEChanging(string value);
    partial void OnCONTAINER_TYPEChanged();
    partial void OnSEAL_NOChanging(string value);
    partial void OnSEAL_NOChanged();
    partial void OnSCAN_LOAD_BYChanging(string value);
    partial void OnSCAN_LOAD_BYChanged();
    partial void OnSCAN_LOAD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSCAN_LOAD_DATEChanged();
    partial void OnSCAN_LOAD_SEQChanging(System.Nullable<long> value);
    partial void OnSCAN_LOAD_SEQChanged();
    partial void OnREMARKSChanging(string value);
    partial void OnREMARKSChanged();
    partial void OnVERSIONChanging(System.Nullable<int> value);
    partial void OnVERSIONChanged();
    partial void OnCREATE_BYChanging(string value);
    partial void OnCREATE_BYChanged();
    partial void OnCREATE_DATEChanging(System.DateTime value);
    partial void OnCREATE_DATEChanged();
    partial void OnMODIFY_BYChanging(string value);
    partial void OnMODIFY_BYChanged();
    partial void OnMODIFY_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFY_DATEChanged();
    partial void OnPACKING_MATERIALSChanging(string value);
    partial void OnPACKING_MATERIALSChanged();
    partial void OnBENCH_NOChanging(string value);
    partial void OnBENCH_NOChanged();
    #endregion
		
		public PACK_CTN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_CENTER", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WORK_CENTER
		{
			get
			{
				return this._WORK_CENTER;
			}
			set
			{
				if ((this._WORK_CENTER != value))
				{
					this.OnWORK_CENTERChanging(value);
					this.SendPropertyChanging();
					this._WORK_CENTER = value;
					this.SendPropertyChanged("WORK_CENTER");
					this.OnWORK_CENTERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STORER_ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STORER_ID
		{
			get
			{
				return this._STORER_ID;
			}
			set
			{
				if ((this._STORER_ID != value))
				{
					this.OnSTORER_IDChanging(value);
					this.SendPropertyChanging();
					this._STORER_ID = value;
					this.SendPropertyChanged("STORER_ID");
					this.OnSTORER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACK_ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PACK_ID
		{
			get
			{
				return this._PACK_ID;
			}
			set
			{
				if ((this._PACK_ID != value))
				{
					this.OnPACK_IDChanging(value);
					this.SendPropertyChanging();
					this._PACK_ID = value;
					this.SendPropertyChanged("PACK_ID");
					this.OnPACK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARTON_NO", DbType="NVarChar(50)")]
		public string CARTON_NO
		{
			get
			{
				return this._CARTON_NO;
			}
			set
			{
				if ((this._CARTON_NO != value))
				{
					this.OnCARTON_NOChanging(value);
					this.SendPropertyChanging();
					this._CARTON_NO = value;
					this.SendPropertyChanged("CARTON_NO");
					this.OnCARTON_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARTON_TYPE", DbType="NVarChar(20)")]
		public string CARTON_TYPE
		{
			get
			{
				return this._CARTON_TYPE;
			}
			set
			{
				if ((this._CARTON_TYPE != value))
				{
					this.OnCARTON_TYPEChanging(value);
					this.SendPropertyChanging();
					this._CARTON_TYPE = value;
					this.SendPropertyChanged("CARTON_TYPE");
					this.OnCARTON_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTN_LINE_SEQ", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long CTN_LINE_SEQ
		{
			get
			{
				return this._CTN_LINE_SEQ;
			}
			set
			{
				if ((this._CTN_LINE_SEQ != value))
				{
					this.OnCTN_LINE_SEQChanging(value);
					this.SendPropertyChanging();
					this._CTN_LINE_SEQ = value;
					this.SendPropertyChanged("CTN_LINE_SEQ");
					this.OnCTN_LINE_SEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LENGTH", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> LENGTH
		{
			get
			{
				return this._LENGTH;
			}
			set
			{
				if ((this._LENGTH != value))
				{
					this.OnLENGTHChanging(value);
					this.SendPropertyChanging();
					this._LENGTH = value;
					this.SendPropertyChanged("LENGTH");
					this.OnLENGTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIDTH", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> WIDTH
		{
			get
			{
				return this._WIDTH;
			}
			set
			{
				if ((this._WIDTH != value))
				{
					this.OnWIDTHChanging(value);
					this.SendPropertyChanging();
					this._WIDTH = value;
					this.SendPropertyChanged("WIDTH");
					this.OnWIDTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEIGHT", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> HEIGHT
		{
			get
			{
				return this._HEIGHT;
			}
			set
			{
				if ((this._HEIGHT != value))
				{
					this.OnHEIGHTChanging(value);
					this.SendPropertyChanging();
					this._HEIGHT = value;
					this.SendPropertyChanged("HEIGHT");
					this.OnHEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTN_VOLUME", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> CTN_VOLUME
		{
			get
			{
				return this._CTN_VOLUME;
			}
			set
			{
				if ((this._CTN_VOLUME != value))
				{
					this.OnCTN_VOLUMEChanging(value);
					this.SendPropertyChanging();
					this._CTN_VOLUME = value;
					this.SendPropertyChanged("CTN_VOLUME");
					this.OnCTN_VOLUMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTN_GROSS_WEIGHT", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> CTN_GROSS_WEIGHT
		{
			get
			{
				return this._CTN_GROSS_WEIGHT;
			}
			set
			{
				if ((this._CTN_GROSS_WEIGHT != value))
				{
					this.OnCTN_GROSS_WEIGHTChanging(value);
					this.SendPropertyChanging();
					this._CTN_GROSS_WEIGHT = value;
					this.SendPropertyChanged("CTN_GROSS_WEIGHT");
					this.OnCTN_GROSS_WEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTN_NET_WEIGHT", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> CTN_NET_WEIGHT
		{
			get
			{
				return this._CTN_NET_WEIGHT;
			}
			set
			{
				if ((this._CTN_NET_WEIGHT != value))
				{
					this.OnCTN_NET_WEIGHTChanging(value);
					this.SendPropertyChanging();
					this._CTN_NET_WEIGHT = value;
					this.SendPropertyChanged("CTN_NET_WEIGHT");
					this.OnCTN_NET_WEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARRIER", DbType="NVarChar(30)")]
		public string CARRIER
		{
			get
			{
				return this._CARRIER;
			}
			set
			{
				if ((this._CARRIER != value))
				{
					this.OnCARRIERChanging(value);
					this.SendPropertyChanging();
					this._CARRIER = value;
					this.SendPropertyChanged("CARRIER");
					this.OnCARRIERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRACKING_NO", DbType="NVarChar(20)")]
		public string TRACKING_NO
		{
			get
			{
				return this._TRACKING_NO;
			}
			set
			{
				if ((this._TRACKING_NO != value))
				{
					this.OnTRACKING_NOChanging(value);
					this.SendPropertyChanging();
					this._TRACKING_NO = value;
					this.SendPropertyChanged("TRACKING_NO");
					this.OnTRACKING_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PALLET_NO", DbType="NVarChar(50)")]
		public string PALLET_NO
		{
			get
			{
				return this._PALLET_NO;
			}
			set
			{
				if ((this._PALLET_NO != value))
				{
					this.OnPALLET_NOChanging(value);
					this.SendPropertyChanging();
					this._PALLET_NO = value;
					this.SendPropertyChanged("PALLET_NO");
					this.OnPALLET_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILD_PALLET_BY", DbType="NVarChar(50)")]
		public string BUILD_PALLET_BY
		{
			get
			{
				return this._BUILD_PALLET_BY;
			}
			set
			{
				if ((this._BUILD_PALLET_BY != value))
				{
					this.OnBUILD_PALLET_BYChanging(value);
					this.SendPropertyChanging();
					this._BUILD_PALLET_BY = value;
					this.SendPropertyChanged("BUILD_PALLET_BY");
					this.OnBUILD_PALLET_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILD_PALLET_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> BUILD_PALLET_DATE
		{
			get
			{
				return this._BUILD_PALLET_DATE;
			}
			set
			{
				if ((this._BUILD_PALLET_DATE != value))
				{
					this.OnBUILD_PALLET_DATEChanging(value);
					this.SendPropertyChanging();
					this._BUILD_PALLET_DATE = value;
					this.SendPropertyChanged("BUILD_PALLET_DATE");
					this.OnBUILD_PALLET_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILD_PALLET_SEQ", DbType="Int")]
		public System.Nullable<int> BUILD_PALLET_SEQ
		{
			get
			{
				return this._BUILD_PALLET_SEQ;
			}
			set
			{
				if ((this._BUILD_PALLET_SEQ != value))
				{
					this.OnBUILD_PALLET_SEQChanging(value);
					this.SendPropertyChanging();
					this._BUILD_PALLET_SEQ = value;
					this.SendPropertyChanged("BUILD_PALLET_SEQ");
					this.OnBUILD_PALLET_SEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTAINER_NO", DbType="NVarChar(50)")]
		public string CONTAINER_NO
		{
			get
			{
				return this._CONTAINER_NO;
			}
			set
			{
				if ((this._CONTAINER_NO != value))
				{
					this.OnCONTAINER_NOChanging(value);
					this.SendPropertyChanging();
					this._CONTAINER_NO = value;
					this.SendPropertyChanged("CONTAINER_NO");
					this.OnCONTAINER_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTAINER_TYPE", DbType="NVarChar(20)")]
		public string CONTAINER_TYPE
		{
			get
			{
				return this._CONTAINER_TYPE;
			}
			set
			{
				if ((this._CONTAINER_TYPE != value))
				{
					this.OnCONTAINER_TYPEChanging(value);
					this.SendPropertyChanging();
					this._CONTAINER_TYPE = value;
					this.SendPropertyChanged("CONTAINER_TYPE");
					this.OnCONTAINER_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEAL_NO", DbType="NVarChar(50)")]
		public string SEAL_NO
		{
			get
			{
				return this._SEAL_NO;
			}
			set
			{
				if ((this._SEAL_NO != value))
				{
					this.OnSEAL_NOChanging(value);
					this.SendPropertyChanging();
					this._SEAL_NO = value;
					this.SendPropertyChanged("SEAL_NO");
					this.OnSEAL_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCAN_LOAD_BY", DbType="NVarChar(50)")]
		public string SCAN_LOAD_BY
		{
			get
			{
				return this._SCAN_LOAD_BY;
			}
			set
			{
				if ((this._SCAN_LOAD_BY != value))
				{
					this.OnSCAN_LOAD_BYChanging(value);
					this.SendPropertyChanging();
					this._SCAN_LOAD_BY = value;
					this.SendPropertyChanged("SCAN_LOAD_BY");
					this.OnSCAN_LOAD_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCAN_LOAD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SCAN_LOAD_DATE
		{
			get
			{
				return this._SCAN_LOAD_DATE;
			}
			set
			{
				if ((this._SCAN_LOAD_DATE != value))
				{
					this.OnSCAN_LOAD_DATEChanging(value);
					this.SendPropertyChanging();
					this._SCAN_LOAD_DATE = value;
					this.SendPropertyChanged("SCAN_LOAD_DATE");
					this.OnSCAN_LOAD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCAN_LOAD_SEQ", DbType="BigInt")]
		public System.Nullable<long> SCAN_LOAD_SEQ
		{
			get
			{
				return this._SCAN_LOAD_SEQ;
			}
			set
			{
				if ((this._SCAN_LOAD_SEQ != value))
				{
					this.OnSCAN_LOAD_SEQChanging(value);
					this.SendPropertyChanging();
					this._SCAN_LOAD_SEQ = value;
					this.SendPropertyChanged("SCAN_LOAD_SEQ");
					this.OnSCAN_LOAD_SEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="NVarChar(200)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this.OnREMARKSChanging(value);
					this.SendPropertyChanging();
					this._REMARKS = value;
					this.SendPropertyChanged("REMARKS");
					this.OnREMARKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION", DbType="Int")]
		public System.Nullable<int> VERSION
		{
			get
			{
				return this._VERSION;
			}
			set
			{
				if ((this._VERSION != value))
				{
					this.OnVERSIONChanging(value);
					this.SendPropertyChanging();
					this._VERSION = value;
					this.SendPropertyChanged("VERSION");
					this.OnVERSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_BY", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CREATE_BY
		{
			get
			{
				return this._CREATE_BY;
			}
			set
			{
				if ((this._CREATE_BY != value))
				{
					this.OnCREATE_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATE_BY = value;
					this.SendPropertyChanged("CREATE_BY");
					this.OnCREATE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFY_BY", DbType="NVarChar(50)")]
		public string MODIFY_BY
		{
			get
			{
				return this._MODIFY_BY;
			}
			set
			{
				if ((this._MODIFY_BY != value))
				{
					this.OnMODIFY_BYChanging(value);
					this.SendPropertyChanging();
					this._MODIFY_BY = value;
					this.SendPropertyChanged("MODIFY_BY");
					this.OnMODIFY_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFY_DATE
		{
			get
			{
				return this._MODIFY_DATE;
			}
			set
			{
				if ((this._MODIFY_DATE != value))
				{
					this.OnMODIFY_DATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFY_DATE = value;
					this.SendPropertyChanged("MODIFY_DATE");
					this.OnMODIFY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACKING_MATERIALS", DbType="NVarChar(50)")]
		public string PACKING_MATERIALS
		{
			get
			{
				return this._PACKING_MATERIALS;
			}
			set
			{
				if ((this._PACKING_MATERIALS != value))
				{
					this.OnPACKING_MATERIALSChanging(value);
					this.SendPropertyChanging();
					this._PACKING_MATERIALS = value;
					this.SendPropertyChanged("PACKING_MATERIALS");
					this.OnPACKING_MATERIALSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BENCH_NO", DbType="NVarChar(30)")]
		public string BENCH_NO
		{
			get
			{
				return this._BENCH_NO;
			}
			set
			{
				if ((this._BENCH_NO != value))
				{
					this.OnBENCH_NOChanging(value);
					this.SendPropertyChanging();
					this._BENCH_NO = value;
					this.SendPropertyChanged("BENCH_NO");
					this.OnBENCH_NOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PACK_HDR")]
	public partial class PACK_HDR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WORK_CENTER;
		
		private string _STORER_ID;
		
		private string _PACK_ID;
		
		private string _STATUS;
		
		private string _PACK_LEVEL;
		
		private System.DateTime _PACK_DATE;
		
		private string _WAVE_ID;
		
		private string _REL_ID;
		
		private System.Nullable<int> _BATCH_NO;
		
		private System.Nullable<int> _PICK_SET_NO;
		
		private System.Nullable<int> _VERSION;
		
		private string _CREATE_BY;
		
		private System.DateTime _CREATE_DATE;
		
		private string _MODIFY_BY;
		
		private System.Nullable<System.DateTime> _MODIFY_DATE;
		
		private string _MEMO;
		
		private string _ORDER_TYPE;
		
		private string _BENCH_NO;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWORK_CENTERChanging(string value);
    partial void OnWORK_CENTERChanged();
    partial void OnSTORER_IDChanging(string value);
    partial void OnSTORER_IDChanged();
    partial void OnPACK_IDChanging(string value);
    partial void OnPACK_IDChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnPACK_LEVELChanging(string value);
    partial void OnPACK_LEVELChanged();
    partial void OnPACK_DATEChanging(System.DateTime value);
    partial void OnPACK_DATEChanged();
    partial void OnWAVE_IDChanging(string value);
    partial void OnWAVE_IDChanged();
    partial void OnREL_IDChanging(string value);
    partial void OnREL_IDChanged();
    partial void OnBATCH_NOChanging(System.Nullable<int> value);
    partial void OnBATCH_NOChanged();
    partial void OnPICK_SET_NOChanging(System.Nullable<int> value);
    partial void OnPICK_SET_NOChanged();
    partial void OnVERSIONChanging(System.Nullable<int> value);
    partial void OnVERSIONChanged();
    partial void OnCREATE_BYChanging(string value);
    partial void OnCREATE_BYChanged();
    partial void OnCREATE_DATEChanging(System.DateTime value);
    partial void OnCREATE_DATEChanged();
    partial void OnMODIFY_BYChanging(string value);
    partial void OnMODIFY_BYChanged();
    partial void OnMODIFY_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFY_DATEChanged();
    partial void OnMEMOChanging(string value);
    partial void OnMEMOChanged();
    partial void OnORDER_TYPEChanging(string value);
    partial void OnORDER_TYPEChanged();
    partial void OnBENCH_NOChanging(string value);
    partial void OnBENCH_NOChanged();
    #endregion
		
		public PACK_HDR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_CENTER", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WORK_CENTER
		{
			get
			{
				return this._WORK_CENTER;
			}
			set
			{
				if ((this._WORK_CENTER != value))
				{
					this.OnWORK_CENTERChanging(value);
					this.SendPropertyChanging();
					this._WORK_CENTER = value;
					this.SendPropertyChanged("WORK_CENTER");
					this.OnWORK_CENTERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STORER_ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STORER_ID
		{
			get
			{
				return this._STORER_ID;
			}
			set
			{
				if ((this._STORER_ID != value))
				{
					this.OnSTORER_IDChanging(value);
					this.SendPropertyChanging();
					this._STORER_ID = value;
					this.SendPropertyChanged("STORER_ID");
					this.OnSTORER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACK_ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PACK_ID
		{
			get
			{
				return this._PACK_ID;
			}
			set
			{
				if ((this._PACK_ID != value))
				{
					this.OnPACK_IDChanging(value);
					this.SendPropertyChanging();
					this._PACK_ID = value;
					this.SendPropertyChanged("PACK_ID");
					this.OnPACK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACK_LEVEL", DbType="NVarChar(10)")]
		public string PACK_LEVEL
		{
			get
			{
				return this._PACK_LEVEL;
			}
			set
			{
				if ((this._PACK_LEVEL != value))
				{
					this.OnPACK_LEVELChanging(value);
					this.SendPropertyChanging();
					this._PACK_LEVEL = value;
					this.SendPropertyChanged("PACK_LEVEL");
					this.OnPACK_LEVELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACK_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime PACK_DATE
		{
			get
			{
				return this._PACK_DATE;
			}
			set
			{
				if ((this._PACK_DATE != value))
				{
					this.OnPACK_DATEChanging(value);
					this.SendPropertyChanging();
					this._PACK_DATE = value;
					this.SendPropertyChanged("PACK_DATE");
					this.OnPACK_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAVE_ID", DbType="NVarChar(20)")]
		public string WAVE_ID
		{
			get
			{
				return this._WAVE_ID;
			}
			set
			{
				if ((this._WAVE_ID != value))
				{
					this.OnWAVE_IDChanging(value);
					this.SendPropertyChanging();
					this._WAVE_ID = value;
					this.SendPropertyChanged("WAVE_ID");
					this.OnWAVE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_ID", DbType="NVarChar(20)")]
		public string REL_ID
		{
			get
			{
				return this._REL_ID;
			}
			set
			{
				if ((this._REL_ID != value))
				{
					this.OnREL_IDChanging(value);
					this.SendPropertyChanging();
					this._REL_ID = value;
					this.SendPropertyChanged("REL_ID");
					this.OnREL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BATCH_NO", DbType="Int")]
		public System.Nullable<int> BATCH_NO
		{
			get
			{
				return this._BATCH_NO;
			}
			set
			{
				if ((this._BATCH_NO != value))
				{
					this.OnBATCH_NOChanging(value);
					this.SendPropertyChanging();
					this._BATCH_NO = value;
					this.SendPropertyChanged("BATCH_NO");
					this.OnBATCH_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PICK_SET_NO", DbType="Int")]
		public System.Nullable<int> PICK_SET_NO
		{
			get
			{
				return this._PICK_SET_NO;
			}
			set
			{
				if ((this._PICK_SET_NO != value))
				{
					this.OnPICK_SET_NOChanging(value);
					this.SendPropertyChanging();
					this._PICK_SET_NO = value;
					this.SendPropertyChanged("PICK_SET_NO");
					this.OnPICK_SET_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION", DbType="Int")]
		public System.Nullable<int> VERSION
		{
			get
			{
				return this._VERSION;
			}
			set
			{
				if ((this._VERSION != value))
				{
					this.OnVERSIONChanging(value);
					this.SendPropertyChanging();
					this._VERSION = value;
					this.SendPropertyChanged("VERSION");
					this.OnVERSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_BY", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CREATE_BY
		{
			get
			{
				return this._CREATE_BY;
			}
			set
			{
				if ((this._CREATE_BY != value))
				{
					this.OnCREATE_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATE_BY = value;
					this.SendPropertyChanged("CREATE_BY");
					this.OnCREATE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFY_BY", DbType="NVarChar(50)")]
		public string MODIFY_BY
		{
			get
			{
				return this._MODIFY_BY;
			}
			set
			{
				if ((this._MODIFY_BY != value))
				{
					this.OnMODIFY_BYChanging(value);
					this.SendPropertyChanging();
					this._MODIFY_BY = value;
					this.SendPropertyChanged("MODIFY_BY");
					this.OnMODIFY_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFY_DATE
		{
			get
			{
				return this._MODIFY_DATE;
			}
			set
			{
				if ((this._MODIFY_DATE != value))
				{
					this.OnMODIFY_DATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFY_DATE = value;
					this.SendPropertyChanged("MODIFY_DATE");
					this.OnMODIFY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMO", DbType="NVarChar(400)")]
		public string MEMO
		{
			get
			{
				return this._MEMO;
			}
			set
			{
				if ((this._MEMO != value))
				{
					this.OnMEMOChanging(value);
					this.SendPropertyChanging();
					this._MEMO = value;
					this.SendPropertyChanged("MEMO");
					this.OnMEMOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDER_TYPE", DbType="NVarChar(10)")]
		public string ORDER_TYPE
		{
			get
			{
				return this._ORDER_TYPE;
			}
			set
			{
				if ((this._ORDER_TYPE != value))
				{
					this.OnORDER_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ORDER_TYPE = value;
					this.SendPropertyChanged("ORDER_TYPE");
					this.OnORDER_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BENCH_NO", DbType="NVarChar(30)")]
		public string BENCH_NO
		{
			get
			{
				return this._BENCH_NO;
			}
			set
			{
				if ((this._BENCH_NO != value))
				{
					this.OnBENCH_NOChanging(value);
					this.SendPropertyChanging();
					this._BENCH_NO = value;
					this.SendPropertyChanged("BENCH_NO");
					this.OnBENCH_NOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PACK_DTL")]
	public partial class PACK_DTL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WORK_CENTER;
		
		private string _STORER_ID;
		
		private string _PACK_ID;
		
		private long _PACK_LINE_SEQ;
		
		private long _CTN_LINE_SEQ;
		
		private string _SKU;
		
		private string _SKU_STATUS;
		
		private System.Nullable<decimal> _QTY;
		
		private System.Nullable<long> _REL_LINE_SEQ;
		
		private long _PICK_LINE_SEQ;
		
		private string _LOT_ID;
		
		private string _ORIGINAL_LOT_ID;
		
		private System.Nullable<int> _VERSION;
		
		private string _CREATE_BY;
		
		private System.DateTime _CREATE_DATE;
		
		private string _MODIFY_BY;
		
		private System.Nullable<System.DateTime> _MODIFY_DATE;
		
		private System.Nullable<System.DateTime> _MANUF_DATE;
		
		private System.Nullable<System.DateTime> _EXPIRY_DATE;
		
		private string _PRODUCT_LOT;
		
		private string _PRODUCT_BATCH;
		
		private string _REL_ID;
		
		private System.Nullable<int> _REL_BATCH_NO;
		
		private System.Nullable<int> _PICK_SET_NO;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWORK_CENTERChanging(string value);
    partial void OnWORK_CENTERChanged();
    partial void OnSTORER_IDChanging(string value);
    partial void OnSTORER_IDChanged();
    partial void OnPACK_IDChanging(string value);
    partial void OnPACK_IDChanged();
    partial void OnPACK_LINE_SEQChanging(long value);
    partial void OnPACK_LINE_SEQChanged();
    partial void OnCTN_LINE_SEQChanging(long value);
    partial void OnCTN_LINE_SEQChanged();
    partial void OnSKUChanging(string value);
    partial void OnSKUChanged();
    partial void OnSKU_STATUSChanging(string value);
    partial void OnSKU_STATUSChanged();
    partial void OnQTYChanging(System.Nullable<decimal> value);
    partial void OnQTYChanged();
    partial void OnREL_LINE_SEQChanging(System.Nullable<long> value);
    partial void OnREL_LINE_SEQChanged();
    partial void OnPICK_LINE_SEQChanging(long value);
    partial void OnPICK_LINE_SEQChanged();
    partial void OnLOT_IDChanging(string value);
    partial void OnLOT_IDChanged();
    partial void OnORIGINAL_LOT_IDChanging(string value);
    partial void OnORIGINAL_LOT_IDChanged();
    partial void OnVERSIONChanging(System.Nullable<int> value);
    partial void OnVERSIONChanged();
    partial void OnCREATE_BYChanging(string value);
    partial void OnCREATE_BYChanged();
    partial void OnCREATE_DATEChanging(System.DateTime value);
    partial void OnCREATE_DATEChanged();
    partial void OnMODIFY_BYChanging(string value);
    partial void OnMODIFY_BYChanged();
    partial void OnMODIFY_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFY_DATEChanged();
    partial void OnMANUF_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMANUF_DATEChanged();
    partial void OnEXPIRY_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEXPIRY_DATEChanged();
    partial void OnPRODUCT_LOTChanging(string value);
    partial void OnPRODUCT_LOTChanged();
    partial void OnPRODUCT_BATCHChanging(string value);
    partial void OnPRODUCT_BATCHChanged();
    partial void OnREL_IDChanging(string value);
    partial void OnREL_IDChanged();
    partial void OnREL_BATCH_NOChanging(System.Nullable<int> value);
    partial void OnREL_BATCH_NOChanged();
    partial void OnPICK_SET_NOChanging(System.Nullable<int> value);
    partial void OnPICK_SET_NOChanged();
    #endregion
		
		public PACK_DTL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_CENTER", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WORK_CENTER
		{
			get
			{
				return this._WORK_CENTER;
			}
			set
			{
				if ((this._WORK_CENTER != value))
				{
					this.OnWORK_CENTERChanging(value);
					this.SendPropertyChanging();
					this._WORK_CENTER = value;
					this.SendPropertyChanged("WORK_CENTER");
					this.OnWORK_CENTERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STORER_ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STORER_ID
		{
			get
			{
				return this._STORER_ID;
			}
			set
			{
				if ((this._STORER_ID != value))
				{
					this.OnSTORER_IDChanging(value);
					this.SendPropertyChanging();
					this._STORER_ID = value;
					this.SendPropertyChanged("STORER_ID");
					this.OnSTORER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACK_ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PACK_ID
		{
			get
			{
				return this._PACK_ID;
			}
			set
			{
				if ((this._PACK_ID != value))
				{
					this.OnPACK_IDChanging(value);
					this.SendPropertyChanging();
					this._PACK_ID = value;
					this.SendPropertyChanged("PACK_ID");
					this.OnPACK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACK_LINE_SEQ", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long PACK_LINE_SEQ
		{
			get
			{
				return this._PACK_LINE_SEQ;
			}
			set
			{
				if ((this._PACK_LINE_SEQ != value))
				{
					this.OnPACK_LINE_SEQChanging(value);
					this.SendPropertyChanging();
					this._PACK_LINE_SEQ = value;
					this.SendPropertyChanged("PACK_LINE_SEQ");
					this.OnPACK_LINE_SEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTN_LINE_SEQ", DbType="BigInt NOT NULL")]
		public long CTN_LINE_SEQ
		{
			get
			{
				return this._CTN_LINE_SEQ;
			}
			set
			{
				if ((this._CTN_LINE_SEQ != value))
				{
					this.OnCTN_LINE_SEQChanging(value);
					this.SendPropertyChanging();
					this._CTN_LINE_SEQ = value;
					this.SendPropertyChanged("CTN_LINE_SEQ");
					this.OnCTN_LINE_SEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU", DbType="NVarChar(50)")]
		public string SKU
		{
			get
			{
				return this._SKU;
			}
			set
			{
				if ((this._SKU != value))
				{
					this.OnSKUChanging(value);
					this.SendPropertyChanging();
					this._SKU = value;
					this.SendPropertyChanged("SKU");
					this.OnSKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU_STATUS", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SKU_STATUS
		{
			get
			{
				return this._SKU_STATUS;
			}
			set
			{
				if ((this._SKU_STATUS != value))
				{
					this.OnSKU_STATUSChanging(value);
					this.SendPropertyChanging();
					this._SKU_STATUS = value;
					this.SendPropertyChanged("SKU_STATUS");
					this.OnSKU_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Decimal(18,8)")]
		public System.Nullable<decimal> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_LINE_SEQ", DbType="BigInt")]
		public System.Nullable<long> REL_LINE_SEQ
		{
			get
			{
				return this._REL_LINE_SEQ;
			}
			set
			{
				if ((this._REL_LINE_SEQ != value))
				{
					this.OnREL_LINE_SEQChanging(value);
					this.SendPropertyChanging();
					this._REL_LINE_SEQ = value;
					this.SendPropertyChanged("REL_LINE_SEQ");
					this.OnREL_LINE_SEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PICK_LINE_SEQ", DbType="BigInt NOT NULL")]
		public long PICK_LINE_SEQ
		{
			get
			{
				return this._PICK_LINE_SEQ;
			}
			set
			{
				if ((this._PICK_LINE_SEQ != value))
				{
					this.OnPICK_LINE_SEQChanging(value);
					this.SendPropertyChanging();
					this._PICK_LINE_SEQ = value;
					this.SendPropertyChanged("PICK_LINE_SEQ");
					this.OnPICK_LINE_SEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOT_ID", DbType="NVarChar(20)")]
		public string LOT_ID
		{
			get
			{
				return this._LOT_ID;
			}
			set
			{
				if ((this._LOT_ID != value))
				{
					this.OnLOT_IDChanging(value);
					this.SendPropertyChanging();
					this._LOT_ID = value;
					this.SendPropertyChanged("LOT_ID");
					this.OnLOT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORIGINAL_LOT_ID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ORIGINAL_LOT_ID
		{
			get
			{
				return this._ORIGINAL_LOT_ID;
			}
			set
			{
				if ((this._ORIGINAL_LOT_ID != value))
				{
					this.OnORIGINAL_LOT_IDChanging(value);
					this.SendPropertyChanging();
					this._ORIGINAL_LOT_ID = value;
					this.SendPropertyChanged("ORIGINAL_LOT_ID");
					this.OnORIGINAL_LOT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSION", DbType="Int")]
		public System.Nullable<int> VERSION
		{
			get
			{
				return this._VERSION;
			}
			set
			{
				if ((this._VERSION != value))
				{
					this.OnVERSIONChanging(value);
					this.SendPropertyChanging();
					this._VERSION = value;
					this.SendPropertyChanged("VERSION");
					this.OnVERSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_BY", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CREATE_BY
		{
			get
			{
				return this._CREATE_BY;
			}
			set
			{
				if ((this._CREATE_BY != value))
				{
					this.OnCREATE_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATE_BY = value;
					this.SendPropertyChanged("CREATE_BY");
					this.OnCREATE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFY_BY", DbType="NVarChar(50)")]
		public string MODIFY_BY
		{
			get
			{
				return this._MODIFY_BY;
			}
			set
			{
				if ((this._MODIFY_BY != value))
				{
					this.OnMODIFY_BYChanging(value);
					this.SendPropertyChanging();
					this._MODIFY_BY = value;
					this.SendPropertyChanged("MODIFY_BY");
					this.OnMODIFY_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFY_DATE
		{
			get
			{
				return this._MODIFY_DATE;
			}
			set
			{
				if ((this._MODIFY_DATE != value))
				{
					this.OnMODIFY_DATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFY_DATE = value;
					this.SendPropertyChanged("MODIFY_DATE");
					this.OnMODIFY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANUF_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MANUF_DATE
		{
			get
			{
				return this._MANUF_DATE;
			}
			set
			{
				if ((this._MANUF_DATE != value))
				{
					this.OnMANUF_DATEChanging(value);
					this.SendPropertyChanging();
					this._MANUF_DATE = value;
					this.SendPropertyChanged("MANUF_DATE");
					this.OnMANUF_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXPIRY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EXPIRY_DATE
		{
			get
			{
				return this._EXPIRY_DATE;
			}
			set
			{
				if ((this._EXPIRY_DATE != value))
				{
					this.OnEXPIRY_DATEChanging(value);
					this.SendPropertyChanging();
					this._EXPIRY_DATE = value;
					this.SendPropertyChanged("EXPIRY_DATE");
					this.OnEXPIRY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_LOT", DbType="NVarChar(50)")]
		public string PRODUCT_LOT
		{
			get
			{
				return this._PRODUCT_LOT;
			}
			set
			{
				if ((this._PRODUCT_LOT != value))
				{
					this.OnPRODUCT_LOTChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_LOT = value;
					this.SendPropertyChanged("PRODUCT_LOT");
					this.OnPRODUCT_LOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_BATCH", DbType="NVarChar(50)")]
		public string PRODUCT_BATCH
		{
			get
			{
				return this._PRODUCT_BATCH;
			}
			set
			{
				if ((this._PRODUCT_BATCH != value))
				{
					this.OnPRODUCT_BATCHChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_BATCH = value;
					this.SendPropertyChanged("PRODUCT_BATCH");
					this.OnPRODUCT_BATCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_ID", DbType="NVarChar(20)")]
		public string REL_ID
		{
			get
			{
				return this._REL_ID;
			}
			set
			{
				if ((this._REL_ID != value))
				{
					this.OnREL_IDChanging(value);
					this.SendPropertyChanging();
					this._REL_ID = value;
					this.SendPropertyChanged("REL_ID");
					this.OnREL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_BATCH_NO", DbType="Int")]
		public System.Nullable<int> REL_BATCH_NO
		{
			get
			{
				return this._REL_BATCH_NO;
			}
			set
			{
				if ((this._REL_BATCH_NO != value))
				{
					this.OnREL_BATCH_NOChanging(value);
					this.SendPropertyChanging();
					this._REL_BATCH_NO = value;
					this.SendPropertyChanged("REL_BATCH_NO");
					this.OnREL_BATCH_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PICK_SET_NO", DbType="Int")]
		public System.Nullable<int> PICK_SET_NO
		{
			get
			{
				return this._PICK_SET_NO;
			}
			set
			{
				if ((this._PICK_SET_NO != value))
				{
					this.OnPICK_SET_NOChanging(value);
					this.SendPropertyChanging();
					this._PICK_SET_NO = value;
					this.SendPropertyChanged("PICK_SET_NO");
					this.OnPICK_SET_NOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
